Refactor CI pipeline

diff --git a/ci/scripts/shipit b/ci/scripts/shipit
--- a/ci/scripts/shipit
+++ b/ci/scripts/shipit
@@ -10,6 +10,37 @@
 
 set -eu
 
+: ${REPO_ROOT:?}
+: ${REPO_OUT:?}
+: ${RELEASE_ROOT:?}
+: ${VERSION_FROM:?}
+: ${AWS_ACCESS_KEY:?}
+: ${AWS_SECRET_KEY:?}
+: ${GIT_EMAIL:?}
+: ${GIT_NAME:?}
+: ${GITHUB_OWNER:?}
+: ${BRANCH:?}
+: ${NOTIFICATION_OUT:?}
+
+if [[ ! -f ${VERSION_FROM} ]]; then
+  echo >&2 "Version file (${VERSION_FROM}) not found. Did you misconfigure Concourse?"
+  exit 1
+fi
+VERSION=$(cat ${VERSION_FROM})
+if [[ -z ${VERSION} ]]; then
+  echo >&2 "Version file (${VERSION_FROM}) was empty. Did you misconfigure Concourse?"
+  exit 1
+fi
+
+if [[ ! -f ${REPO_ROOT}/ci/release_notes.md ]]; then
+  echo >&2 "ci/release_notes.md not found. Did you forget to write them?"
+  exit 1
+fi
+
+DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
+
+###############################################################
+
 header() {
 	echo
 	echo "###############################################"
@@ -18,100 +49,77 @@ header() {
 	echo
 }
 
-: ${REPO_ROOT:?required}
-: ${RELEASE_ROOT:?required}
-: ${REPO_OUT:?required}
-: ${BRANCH:?required}
-: ${GITHUB_OWNER:?required}
-: ${VERSION_FROM:?required}
-: ${AWS_ACCESS_KEY:?required}
-: ${AWS_SECRET_KEY:?required}
-
-if [[ ! -f ${VERSION_FROM} ]]; then
-  echo >&2 "Version file (${VERSION_FROM}) not found.  Did you misconfigure Concourse?"
-  exit 2
-fi
-VERSION=$(cat ${VERSION_FROM})
-if [[ -z ${VERSION} ]]; then
-  echo >&2 "Version file (${VERSION_FROM}) was empty.  Did you misconfigure Concourse?"
-  exit 2
-fi
-
-if [[ ! -f ${REPO_ROOT}/ci/release_notes.md ]]; then
-  echo >&2 "ci/release_notes.md not found.  Did you forget to write them?"
-  exit 1
-fi
-
-DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
-
 ###############################################################
 
+header "Creating final release..."
 cd ${REPO_ROOT}
-RELEASE_NAME=$(bosh2 int config/final.yml --path /final_name)
-
-cat > config/private.yml <<YAML
+git submodule update --init --recursive --force
+cat > config/private.yml <<EOF
 ---
 blobstore:
   provider: s3
   options:
     access_key_id: ${AWS_ACCESS_KEY}
     secret_access_key: ${AWS_SECRET_KEY}
-YAML
-
-header "Pulling in any git submodules..."
-git submodule update --init --recursive --force
-
-header "Create final release..."
-bosh2 -n create-release --final --version "${VERSION}"
-bosh2 -n create-release releases/$RELEASE_NAME/$RELEASE_NAME-$VERSION.yml \
-              --tarball releases/$RELEASE_NAME/$RELEASE_NAME-$VERSION.tgz
+EOF
+RELEASE_NAME=$(bosh int config/final.yml --path /final_name)
+bosh -n create-release --final --version "${VERSION}"
+bosh -n create-release releases/${RELEASE_NAME}/${RELEASE_NAME}-${VERSION}.yml \
+        --tarball releases/${RELEASE_NAME}/${RELEASE_NAME}-${VERSION}.tgz
 cd -
 
-RELEASE_TGZ=$REPO_ROOT/releases/$RELEASE_NAME/$RELEASE_NAME-$VERSION.tgz
-export SHA1=$(sha1sum $RELEASE_TGZ | head -n1 | awk '{print $1}')
-echo "SHA1=$SHA1"
+###############################################################
 
+header "Generating github release artifacts..."
+RELEASE_TGZ=${REPO_ROOT}/releases/${RELEASE_NAME}/${RELEASE_NAME}-${VERSION}.tgz
+SHA1=$(sha1sum ${RELEASE_TGZ} | head -n1 | awk '{print $1}')
 mkdir -p ${RELEASE_ROOT}/artifacts
-echo "v${VERSION}"                         > ${RELEASE_ROOT}/tag
+mv ${RELEASE_TGZ}                            ${RELEASE_ROOT}/artifacts
 echo "v${VERSION}"                         > ${RELEASE_ROOT}/name
-mv ${REPO_ROOT}/releases/*/*-${VERSION}.tgz  ${RELEASE_ROOT}/artifacts
+echo "v${VERSION}"                         > ${RELEASE_ROOT}/tag
 mv ${REPO_ROOT}/ci/release_notes.md          ${RELEASE_ROOT}/notes.md
 cat >> ${RELEASE_ROOT}/notes.md <<EOF
-
-### Deployment
+## Deployment
 \`\`\`yaml
 releases:
-- name: $RELEASE_NAME
-  version: $VERSION
-  url: https://github.com/${GITHUB_OWNER}/${RELEASE_NAME}-boshrelease/releases/download/v${VERSION}/${RELEASE_NAME}-${VERSION}.tgz
-  sha1: $SHA1
+  - name: ${RELEASE_NAME}
+    version: ${VERSION}
+    url: https://github.com/${GITHUB_OWNER}/${RELEASE_NAME}-boshrelease/releases/download/v${VERSION}/${RELEASE_NAME}-${VERSION}.tgz
+    sha1: ${SHA1}
 \`\`\`
 EOF
-cat > ${RELEASE_ROOT}/notification <<EOF
-<!here> New ${RELEASE_NAME} v${VERSION} released!
-EOF
 
+###############################################################
 
-header "Update git repo with final release..."
+header "Updating git repo with final release..."
 if [[ -z $(git config --global user.email) ]]; then
-  git config --global user.email "ci@starkandwayne.com"
+  git config --global user.email "${GIT_EMAIL}"
 fi
 if [[ -z $(git config --global user.name) ]]; then
-  git config --global user.name "CI Bot"
+  git config --global user.name "${GIT_NAME}"
 fi
 
-(cd ${REPO_ROOT}
- for MANIFEST_PATH in $(ls manifests/*.yml); do
-   $DIR/update-manifest $GITHUB_OWNER $RELEASE_NAME $VERSION $SHA1 $MANIFEST_PATH
- done
- git merge --no-edit ${BRANCH}
- git add -A
- git status
- git commit -m "release v${VERSION}")
+cd ${REPO_ROOT}
+for MANIFEST_PATH in $(ls manifests/*.yml); do
+  ${DIR}/update-manifest ${GITHUB_OWNER} ${RELEASE_NAME} ${VERSION} ${SHA1} ${MANIFEST_PATH}
+done
+git merge --no-edit ${BRANCH}
+git add -A
+git status
+git commit -m "${RELEASE_NAME} BOSH release v${VERSION}"
+cd -
 
-# so that future steps in the pipeline can push our changes
 cp -a ${REPO_ROOT} ${REPO_OUT}
 
-cat > ${NOTIFICATION_OUT:-notifications}/message <<EOS
-New ${RELEASE_NAME} v${VERSION} released. <https://github.com/${GITHUB_OWNER}/${RELEASE_NAME}-boshrelease/releases/tag/v${VERSION}|Release notes>.
-EOS
+###############################################################
+
+header "Generating notification message..."
+cat > ${NOTIFICATION_OUT}/message <<EOF
+New ${RELEASE_NAME} BOSH release v${VERSION} released. <https://github.com/${GITHUB_OWNER}/${RELEASE_NAME}-boshrelease/releases/tag/v${VERSION}|Release notes>.
+EOF
+
+###############################################################
+
+header "SUCCESS"
+
+exit 0
diff --git a/ci/scripts/testflight b/ci/scripts/testflight
--- a/ci/scripts/testflight
+++ b/ci/scripts/testflight
@@ -2,9 +2,36 @@
 #
 # ci/scripts/testflight
 #
-# Script for testing a BOSH release using bosh2
+# Script for testing a BOSH release using bosh
 #
 # author:  James Hunt <james@niftylogic.com>
+
+set -e
+
+: ${REPO_ROOT:?}
+: ${AWS_ACCESS_KEY:?}
+: ${AWS_SECRET_KEY:?}
+: ${STEMCELL:?}
+: ${BOSH_DEPLOYMENT:?}
+: ${MANIFEST_PATH:?}
+
+if [[ ! -f ${REPO_ROOT}/${MANIFEST_PATH} ]]; then
+	echo "Deployment manifest ${MANIFEST_PATH} does not exist"
+	exit 1
+fi
+
+op_file_errors=
+for op_file in ${MANIFEST_OP_PATHS//,/ }; do
+	if [[ ! -f  ${REPO_ROOT}/$op_file ]]; then
+		op_file_errors=1
+		echo "Operator file missing: ${op_file}"
+	fi
+done
+if [[ ! -z ${op_file_errors} ]]; then
+	exit 1
+fi
+
+###############################################################
 
 header() {
 	echo
@@ -14,149 +41,115 @@ header() {
 	echo
 }
 
-#!/bin/bash
+###############################################################
 
-set -e
+header "Starting bosh..."
+/usr/local/bin/start-bosh
+source /tmp/local-bosh/director/env
 
-: ${BOSH_ENVIRONMENT:?required}
-: ${BOSH_CA_CERT:?required}
-: ${BOSH_CLIENT:?required}
-: ${BOSH_CLIENT_SECRET:?required}
-: ${BOSH_DEPLOYMENT:?required}
-: ${MANIFEST_PATH:?required}
-: ${AWS_ACCESS_KEY:?required}
-: ${AWS_SECRET_KEY:?required}
+###############################################################
 
-cd ${REPO_ROOT:?required}
-header "Pulling in any git submodules..."
+header "Uploading stemcell..."
+bosh -n upload-stemcell ${STEMCELL}
+
+###############################################################
+
+header "Creating candidate release..."
+cd ${REPO_ROOT}
 git submodule update --init --recursive --force
-
-header "Confirming testflight inputs"
-
-echo "Confirming deployment manifest ${MANIFEST_PATH} exists"
-if [[ ! -f ${MANIFEST_PATH} ]]; then
-	echo "Deployment manifest ${MANIFEST_PATH} does not exist"
-	exit 1
-fi
-
-echo "Confirming that \$MANIFEST_VARS is valid"
-mkdir -p tmp
-
-# $MANIFEST_VARS can either be "key: value" or "key=value"
-# and will be converted to "key: value" YAML
-echo "${MANIFEST_VARS:-"{} ---"}" | sed -e "s/ *= */: /g" > tmp/vars.yml
-if [[ ! -z $DEBUG ]]; then
-	echo "Variables passed to deployment manifest:"
-	cat tmp/vars.yml
-fi
-# convert YAML to JSON to check YAML validity
-spruce json tmp/vars.yml > /dev/null
-
-echo "Confirming each operator file exists: ${MANIFEST_OP_PATHS:-ok, none specified.}"
-op_patch_file_errors=
-for op_patch_file in ${MANIFEST_OP_PATHS//,/ } ; do
-	if [[ ! -f $op_patch_file ]]; then
-		op_patch_file_errors=1
-		echo "Operator file missing: ${op_patch_file}"
-	fi
-done
-if [[ ! -z ${op_patch_file_errors} ]]; then
-	exit 1
-fi
-
-
-header "Cleaning up from any previous deployments..."
-bosh2 -n delete-deployment
-
-header "Creating candidate BOSH release..."
-bosh2 -n reset-release # in case dev_releases/ is in repo accidentally
-
-cat > config/private.yml <<YAML
+cat > config/private.yml <<EOF
 ---
 blobstore:
   provider: s3
   options:
     access_key_id: ${AWS_ACCESS_KEY}
     secret_access_key: ${AWS_SECRET_KEY}
-YAML
-bosh2 create-release
-bosh2 upload-release --rebase
+EOF
+bosh -n reset-release
+bosh -n create-release
+cd -
 
-header "Deploying to ${BOSH_ENVIRONMENT}..."
-release_name=$(bosh2 int config/final.yml --path /final_name)
+###############################################################
 
-header "Choosing cloud-config options"
-vm_type=$(bosh2 int <(bosh2 cloud-config) --path /vm_types/0/name)
-disk_type=$(bosh2 int <(bosh2 cloud-config) --path /disk_types/0/name)
-network=$(bosh2 int <(bosh2 cloud-config) --path /networks/0/name)
+header "Uploading candidate release..."
+cd ${REPO_ROOT}
+bosh -n upload-release --rebase
+cd -
 
-release_final_version=$(spruce json dev_releases/*/index.yml | jq -r ".builds[].version" | sed -e "s%+.*%%")
-release_dev_version="${release_final_version}.latest"
+###############################################################
 
-cat > tmp/deployment.yml <<YAML
+header "Generating deployment manifest..."
+cd ${REPO_ROOT}
+mkdir -p tmp
+
+RELEASE_NAME=$(bosh int config/final.yml --path /final_name)
+cat > tmp/deployment.yml <<EOF
 ---
 - type: replace
   path: /name
   value: ${BOSH_DEPLOYMENT}
-
 - type: replace
-  path: /releases/name=${release_name}
+  path: /releases/name=${RELEASE_NAME}
   value:
-    name: ${release_name}
-    version: ${release_dev_version}
-YAML
+    name: ${RELEASE_NAME}
+    version: latest
+EOF
 
+VM_TYPE=$(bosh int <(bosh cloud-config) --path /vm_types/0/name)
+DISK_TYPE=$(bosh int <(bosh cloud-config) --path /disk_types/0/name)
+NETWORK=$(bosh int <(bosh cloud-config) --path /networks/0/name)
+AZ=$(bosh int <(bosh cloud-config) --path /azs/0/name)
 for ig_name in $(spruce json ${MANIFEST_PATH} | jq -r ".instance_groups[].name"); do
-cat >> tmp/deployment.yml <<YAML
+cat >> tmp/deployment.yml <<EOF
 - type: replace
   path: /instance_groups/name=${ig_name}/vm_type
-  value: ${vm_type}
-
+  value: ${VM_TYPE}
 - type: replace
   path: /instance_groups/name=${ig_name}/persistent_disk_type?
-  value: ${disk_type}
-
+  value: ${DISK_TYPE}
 - type: replace
   path: /instance_groups/name=${ig_name}/networks
-  value: [{name: ${network}}]
-YAML
+  value: [{name: ${NETWORK}}]
+- type: replace
+  path: /instance_groups/name=${ig_name}/azs
+  value: [${AZ}]
+EOF
 done
 
-op_patch_files_flags=""
-for op_patch_file in ${MANIFEST_OP_PATHS//,/ } ; do
-   op_patch_files_flags="${op_patch_files_flags} -o $op_patch_file"
+OP_FILES_FLAGS=""
+for op_file in ${MANIFEST_OP_PATHS//,/ }; do
+   OP_FILES_FLAGS="${OP_FILES_FLAGS} -o $op_file"
 done
 
-set -x
+echo "${MANIFEST_VARS:-"{} ---"}" | sed -e "s/ *= */: /g" > tmp/vars.yml
 
-bosh2 int ${MANIFEST_PATH} \
-  -o tmp/deployment.yml    \
-  ${op_patch_files_flags}            \
+bosh int ${MANIFEST_PATH}    \
+  -o tmp/deployment.yml      \
+  ${OP_FILES_FLAGS}          \
   --vars-store tmp/creds.yml \
   --vars-file  tmp/vars.yml  \
-  --var-errs \
-    > tmp/manifest.yml
+  --var-errs                 \
+  > tmp/manifest.yml
+cd -
 
-bosh2 -n deploy tmp/manifest.yml
+###############################################################
 
-TEST_ERRAND=${TEST_ERRAND:-} # backwards compatibility
-TEST_ERRANDS=${TEST_ERRANDS:-$TEST_ERRAND}
-if [[ -n ${TEST_ERRANDS} ]]; then
-	for errand in ${TEST_ERRANDS}; do
-		header "Running '${errand}' errand"
-		bosh2 -n run-errand ${errand}
+header "Deploying candidate release..."
+cd ${REPO_ROOT}
+bosh -n deploy tmp/manifest.yml
+cd -
+
+###############################################################
+
+if [[ -n ${TEST_ERRANDS:-} ]]; then
+  for errand in ${TEST_ERRANDS}; do
+		header "Running '${errand}' errand..."
+		bosh -n run-errand ${errand}
 	done
-else
-	echo "No test errands specified, skipping."
 fi
 
-if [[ -z ${SKIP_DELETE_DEPLOYMENT:-} ]]; then
-	header "Cleaning up after successful deployment..."
-	bosh2 -n delete-deployment
-else
-	header "Skipping cleanup of successful deployment."
-fi
+###############################################################
 
-echo
-echo "SUCCESS"
+header "SUCCESS"
+
 exit 0
